### ISSUE TITLE
How to use socks ?

### ISSUE THREAD

**Issue by marsianiniskalaia** [kaliiiiiiiiii/Selenium-Injector#6]
Can use socks5 i try its not connnected

**Comment by ttlns** [comment]
Chrome doesn't support socks5 with authentification - you can look it up.

You can try
1. Using a middleware proxy
2. using a custom compiled chromium browser

**Comment by marsianiniskalaia** [comment]
Okey thanks sir i Will try .

Sel, 23 Jul 2024 pukul 23.22 kaliiiiiiiiiii ***@***.***>
menulis:
